### ISSUE TITLE
Can't run node app.js error on SocketHallEvents.js

### ISSUE THREAD

**Issue by hyvraine** [pedrooaugusto/UNO-card-game#1]
I'm not knowledgeable with the components of the MERN stack.

I can't seem to run the server with the command node SocketHallEvents.js
It gives me the SyntaxError: missing ) after argument list starting at line 17

It looks like it doesn't acknowledge the async and await commands, weird.

SocketHallEvents.js:17
    socket.on("/hall/join-room/check", async this => {
                                       ^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> ([[__webremoved]]\unogame\server\app.js:4:20)

Please help, thank you!

**Comment by pedrooaugusto** [comment]
@marqroldan 

What is your current NodeJS version ?
